version: '3.8'
services:
  nginx:
    ports:
      - "4000:80"
  node-mohit-app:
    build: 
      context: . 
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=mohit
      - MONGO_PASS=123456789
      - SESSION_SECRET=secret
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mohit
      - MONGO_INITDB_ROOT_PASSWORD=123456789
