version: '3.8'
services:
  nginx:
    ports:
      - "80:80"
  node-mohit-app:
    build: 
      context: .
      args:
        - NODE_ENV=production
        - MONGO_USER=${MONGO_USER}
        - MONGO_PASS=${MONGO_PASS}
        - SESSION_SECRET=${SESSION_SECRET}
    environment:
      - NODE_ENV=production
    command: node server.js
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}