version: '3.8'
services:
  nginx:
    ports:
      - "80:80"
  node-mohit-app:
    build: 
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: node server.js